# На какой группе серверов
- hosts: webservers

  tasks:
    - name: uninstall git
      become: yes
      ansible.builtin.apt: # имя модуля Ansible
        name: git
        state: absent
       
    - name: remove gitconfigs
      file:
        state: absent
        path: "/home/{{ item.name }}/.gitconfig"
      loop: "{{ users }}"
      become: yes
