- hosts: webservers
    
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
      become: yes
      
    - name: Creates directory
      file: path={{root_dir}} state=directory mode=0755

    - name: update nginx config
      template: src=templates/nginx.conf.j2 dest={{nginx_conf_dir}}/nginx.conf
      notify:
        - restart nginx
      become: yes

    - name: copy index.html
      template: src=templates/index.html.j2 dest={{root_dir}}/index.html mode=0777
      become: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes
